---
version: '3'
services:
  mongodb-0:
    network_mode: host
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    command: --replSet=rs --port=65017
  mongodb-1:
    network_mode: host
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    command: --replSet=rs --port=65018
  mongodb-2:
    network_mode: host
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    command: --replSet=rs --port=65019
  init:
    network_mode: host
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    entrypoint: /bin/bash
    command: /init-test-replset.sh
    volumes:
      - ./scripts/init-test-replset.sh:/init-test-replset.sh:ro 
    depends_on:
      - mongodb-0
